package hello;

import ch.qos.logback.core.net.SyslogOutputStream;
import com.fasterxml.jackson.databind.util.JSONPObject;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import hello.Todo;
import hello.UserRepository;
import java.io.PrintWriter;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@PostMapping(path="/add" )
	public @ResponseBody String addNewUser (@RequestBody Todo u) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		System.out.println(u);
		userRepository.save(u);
		return "Saved";
	}

	@PostMapping(path = "delete")
	public  @ResponseBody String deleteUser(@RequestBody Todo u){

		userRepository.delete(u);
		return "DELETED!";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Todo> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

}
